"""empty message

Revision ID: 433dfb0d51fd
Revises: 5f778b82368e
Create Date: 2023-10-04 17:10:46.168955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433dfb0d51fd'
down_revision = '5f778b82368e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
