"""empty message

Revision ID: a992549bb65c
Revises: 3c6c51c6ec53
Create Date: 2023-10-12 00:45:03.744683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a992549bb65c'
down_revision = '3c6c51c6ec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_date', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.String(length=80), nullable=False),
    sa.Column('event_location', sa.String(length=80), nullable=False),
    sa.Column('event_description', sa.String(length=80), nullable=False),
    sa.Column('event_image', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('magic_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('favorite_type', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['magic_id'], ['magic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('magic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['magic_id'], ['magic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('Magic')
    op.drop_table('Favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorites_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('magic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('magic_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorite_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['magic_id'], ['Magic.id'], name='Favorites_magic_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorites_pkey')
    )
    op.create_table('Magic',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Magic_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Magic_pkey')
    )
    op.drop_table('magic_users')
    op.drop_table('favorites')
    op.drop_table('event_users')
    op.drop_table('magic')
    op.drop_table('events')
    # ### end Alembic commands ###
