"""empty message

Revision ID: b98789e250e9
Revises: e7e464ffbefa
Create Date: 2023-10-12 23:03:16.036875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98789e250e9'
down_revision = 'e7e464ffbefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
