"""empty message

Revision ID: da34bb2ce4ce
Revises: 0e549f1a5814
Create Date: 2023-10-10 12:50:43.855429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da34bb2ce4ce'
down_revision = '0e549f1a5814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_type', sa.String(length=80), nullable=True))
        batch_op.alter_column('magic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('magic_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.alter_column('magic_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('magic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('favorite_type')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
