"""empty message

Revision ID: e7e464ffbefa
Revises: da34bb2ce4ce
Create Date: 2023-10-12 23:01:07.983121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e464ffbefa'
down_revision = 'da34bb2ce4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Magic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Magic', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
