"""empty message

Revision ID: fecff9c75d87
Revises: 433dfb0d51fd
Create Date: 2023-10-04 19:16:27.458291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecff9c75d87'
down_revision = '433dfb0d51fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_method', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
